name: i9xp_commerce
description: A Flutter project application that allow users to interact with an e-commerce experience.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_money_formatter: ^0.8.3
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  carousel_slider: ^2.2.1
  json_annotation: ^3.0.1
  flutter_icons: ^1.1.0
  shimmer: ^1.1.1
  sqflite: ^1.3.1
  share: ^0.6.4+3
  intl: ^0.15.8
  dio: ^3.0.9
  get: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/neusa-next-std/NeusaNextStd-Light.otf
          weight: 300
        - asset: assets/fonts/neusa-next-std/NeusaNextStd-Regular.otf
          weight: 400
        - asset: assets/fonts/neusa-next-std/NeusaNextStd-Medium.otf
          weight: 500
        - asset: assets/fonts/neusa-next-std/NeusaNextStd-Regular.otf
          weight: 700
  assets:
    - assets/images/